// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/wfc-changes/DuplicateWarning.tsx": () => import("../components/mockups/wfc-changes/DuplicateWarning.tsx"),
  "./components/mockups/wfc-changes/LockedInputs.tsx": () => import("../components/mockups/wfc-changes/LockedInputs.tsx"),
  "./components/mockups/wfc-changes/RejoinRoster.tsx": () => import("../components/mockups/wfc-changes/RejoinRoster.tsx"),
  "./components/mockups/wfc-changes/StandardPlay.tsx": () => import("../components/mockups/wfc-changes/StandardPlay.tsx"),
  "./components/mockups/wfc-changes/TapForPar.tsx": () => import("../components/mockups/wfc-changes/TapForPar.tsx")
};
